import type { IbisGraph, NormalizedTranscript, PipelineJob } from "@/lib/contracts";

export const demoYoutubeUrl = "https://www.youtube.com/watch?v=lu0ic3L3Z3k";

export const demoJob: PipelineJob = {
  id: "job_demo_youtube",
  title: "Curated YouTube debate",
  status: "ready",
  createdAt: "2026-06-20T20:30:00.000Z",
  updatedAt: "2026-06-20T20:35:00.000Z",
  traceId: "phoenix-demo-trace",
  source: {
    id: "src_demo_youtube",
    inputUrl: demoYoutubeUrl,
    canonicalUrl: demoYoutubeUrl,
    sourceType: "youtube",
    title: "Short debate video",
    fetchedAt: "2026-06-20T20:31:00.000Z",
  },
  steps: [
    {
      id: "source_capture",
      label: "Source capture",
      status: "complete",
      detail: "Source context and metadata captured.",
    },
    {
      id: "audio_extract",
      label: "Audio extraction",
      status: "complete",
      detail: "Permitted demo audio normalized for transcription.",
    },
    {
      id: "deepgram_transcribe",
      label: "Deepgram transcription",
      status: "complete",
      detail: "Speaker-timed utterances with confidence scores.",
    },
    {
      id: "ibis_extract",
      label: "IBIS extraction",
      status: "complete",
      detail: "Anthropic converted utterances into issue-centered nodes.",
    },
    {
      id: "ibis_validate",
      label: "Graph validation",
      status: "warning",
      detail: "One low-confidence evidence span needs review.",
    },
    {
      id: "map_build",
      label: "Map build",
      status: "complete",
      detail: "Editable workspace payload is ready.",
    },
  ],
  artifacts: [
    { kind: "source", label: "Source capture", path: "data/jobs/job_demo_youtube/source.json" },
    { kind: "audio", label: "Extracted source audio", path: "data/jobs/job_demo_youtube/audio/source.wav" },
    { kind: "transcript", label: "Normalized Deepgram transcript", path: "data/jobs/job_demo_youtube/transcript.json" },
    { kind: "graph", label: "Validated IBIS graph", path: "data/jobs/job_demo_youtube/graph.json" },
    { kind: "trace", label: "Phoenix trace", path: "phoenix-demo-trace" },
  ],
};

export const demoTranscript: NormalizedTranscript = {
  type: "normalized_transcript",
  version: 1,
  durationSec: 142,
  deepgramRequestId: "dg_demo_request",
  source: demoJob.source,
  summary: "A short discussion about whether cities should restrict private cars downtown.",
  utterances: [
    {
      id: "u1",
      speakerId: "speaker_0",
      speakerLabel: "Moderator",
      startSec: 0.4,
      endSec: 5.8,
      confidence: 0.94,
      text: "Should cities restrict private cars downtown?",
    },
    {
      id: "u2",
      speakerId: "speaker_1",
      speakerLabel: "Maya",
      startSec: 7.1,
      endSec: 18.6,
      confidence: 0.91,
      text: "Restricting cars downtown gives people cleaner air and safer streets.",
    },
    {
      id: "u3",
      speakerId: "speaker_2",
      speakerLabel: "Jonas",
      startSec: 21.2,
      endSec: 35.4,
      confidence: 0.88,
      text: "A broad restriction can punish workers who cannot afford to live near transit.",
    },
    {
      id: "u4",
      speakerId: "speaker_1",
      speakerLabel: "Maya",
      startSec: 39.2,
      endSec: 52.6,
      confidence: 0.86,
      text: "The restriction should begin with delivery windows, disabled access, and transit expansion.",
    },
    {
      id: "u5",
      speakerId: "speaker_2",
      speakerLabel: "Jonas",
      startSec: 56.4,
      endSec: 71.9,
      confidence: 0.79,
      text: "If transit investment comes first, I could support a car-light district.",
    },
  ],
  fullText:
    "Moderator: Should cities restrict private cars downtown?\nMaya: Restricting cars downtown gives people cleaner air and safer streets.\nJonas: A broad restriction can punish workers who cannot afford to live near transit.\nMaya: The restriction should begin with delivery windows, disabled access, and transit expansion.\nJonas: If transit investment comes first, I could support a car-light district.",
};

export const demoGraph: IbisGraph = {
  type: "ibis_graph",
  version: 1,
  title: "Should cities restrict private cars downtown?",
  summary: "The map centers on sequencing: whether restrictions should happen before or after transit access improves.",
  sourceId: demoJob.source.id,
  warnings: ["Node n5 uses a lower-confidence transcript span and needs review."],
  nodes: [
    {
      id: "n1",
      type: "issue",
      label: "Should cities restrict private cars downtown?",
      transcriptSpanIds: ["u1"],
      quote: demoTranscript.utterances[0].text,
      timestampStartMs: 400,
      timestampEndMs: 5800,
      confidence: "high",
      position: { x: 420, y: 170 },
      createdFrom: "ai",
      reviewed: true,
    },
    {
      id: "n2",
      type: "position",
      label: "Restrict downtown cars to improve streets",
      transcriptSpanIds: ["u2"],
      quote: demoTranscript.utterances[1].text,
      timestampStartMs: 7100,
      timestampEndMs: 18600,
      confidence: "high",
      position: { x: 720, y: 170 },
      createdFrom: "ai",
    },
    {
      id: "n3",
      type: "pro",
      label: "Cleaner air and safer streets",
      transcriptSpanIds: ["u2"],
      quote: demoTranscript.utterances[1].text,
      timestampStartMs: 7100,
      timestampEndMs: 18600,
      confidence: "high",
      position: { x: 920, y: 80 },
      createdFrom: "ai",
    },
    {
      id: "n4",
      type: "con",
      label: "May punish workers far from transit",
      transcriptSpanIds: ["u3"],
      quote: demoTranscript.utterances[2].text,
      timestampStartMs: 21200,
      timestampEndMs: 35400,
      confidence: "medium",
      position: { x: 920, y: 260 },
      createdFrom: "ai",
    },
    {
      id: "n5",
      type: "position",
      label: "Start with access and transit expansion",
      transcriptSpanIds: ["u4", "u5"],
      quote: demoTranscript.utterances[3].text,
      timestampStartMs: 39200,
      timestampEndMs: 71900,
      confidence: "medium",
      position: { x: 700, y: 390 },
      createdFrom: "ai",
      warnings: ["Review lower-confidence support from u5."],
    },
  ],
  edges: [
    {
      id: "e1",
      type: "answers",
      source: "n2",
      target: "n1",
      confidence: "high",
      transcriptSpanIds: ["u2"],
      createdFrom: "ai",
    },
    {
      id: "e2",
      type: "supports",
      source: "n3",
      target: "n2",
      confidence: "high",
      transcriptSpanIds: ["u2"],
      createdFrom: "ai",
    },
    {
      id: "e3",
      type: "objects_to",
      source: "n4",
      target: "n2",
      confidence: "medium",
      transcriptSpanIds: ["u3"],
      createdFrom: "ai",
    },
    {
      id: "e4",
      type: "answers",
      source: "n5",
      target: "n1",
      confidence: "medium",
      transcriptSpanIds: ["u4", "u5"],
      createdFrom: "ai",
    },
  ],
};
